.TH mod-ssl-makecert 8 "5 Mar 2003" "" "libapache-mod-ssl"
.SH NAME
mod-ssl-makecert \- utility to create SSL certificates
.SH SYNOPSIS
.B mod-ssl-makecert
.SH DESCRIPTION
.B mod-ssl-makecert
is a very simple interactive utility to create keys and certificates
in /etc/apache/ssl.*/ hierarchy.
.SH SEE ALSO
.BR openssl (1)
